-- Thêm dữ liệu vào bảng Reviews
INSERT INTO Reviews (product_id, user_id, rating, comment)
VALUES
(1, 1, 4, 'Sản phẩm tốt, nhưng giao hàng chậm.'),
(2, 2, 5, 'Chất lượng sản phẩm tuyệt vời, giao hàng nhanh chóng!'),
(3, 3, 3, 'Sản phẩm không như mong đợi, giá hơi cao.'),
(4, 4, 4, 'Dễ sử dụng, chất lượng ổn định, nhưng cần cải thiện bao bì.'),
(5, 5, 5, 'Tuyệt vời! Tôi sẽ mua lại sản phẩm này.'),
(6, 6, 4, 'Chất lượng tốt nhưng sản phẩm hơi nhỏ hơn tưởng tượng.'),
(7, 7, 3, 'Sản phẩm không đúng mô tả trên website.'),
(8, 8, 5, 'Chất lượng vượt xa mong đợi, đáng mua.'),
(9, 9, 4, 'Dùng rất ổn, tuy nhiên hơi nặng tay.'),
(10, 10, 2, 'Không hài lòng về chất lượng, sẽ không mua lần nữa.'),
(1, 11, 3, 'Chất lượng trung bình, giá hơi cao.'),
(2, 12, 5, 'Sản phẩm tuyệt vời, tôi rất thích!'),
(3, 13, 4, 'Sản phẩm khá ổn, chỉ hơi thiếu một số tính năng.'),
(4, 14, 3, 'Sản phẩm tốt nhưng giá cả hơi đắt.'),
(5, 15, 4, 'Chất lượng ok, tuy nhiên hơi lâu để nhận được hàng.'),
(6, 16, 5, 'Rất hài lòng, sẽ mua thêm nếu có cơ hội.'),
(7, 17, 4, 'Sản phẩm phù hợp với giá tiền.'),
(8, 18, 3, 'Không đạt yêu cầu, sẽ không mua lại.'),
(9, 19, 5, 'Sản phẩm chất lượng tuyệt vời, rất đáng giá!'),
(10, 20, 2, 'Không như mô tả, không hài lòng về sản phẩm.'),
(1, 21, 4, 'Chất lượng khá tốt, giao hàng nhanh chóng.'),
(2, 22, 5, 'Đặc biệt tốt, rất hài lòng!'),
(3, 23, 4, 'Sản phẩm ổn, nhưng cần cải tiến hơn.'),
(4, 24, 3, 'Sản phẩm tốt nhưng không giống với hình ảnh quảng cáo.'),
(5, 25, 5, 'Tuyệt vời, chất lượng tốt hơn mong đợi.'),
(6, 26, 4, 'Dễ sử dụng, nhưng cần thêm tính năng.'),
(7, 27, 3, 'Sản phẩm bình thường, không có gì nổi bật.'),
(8, 28, 4, 'Chất lượng khá tốt, nhưng có thể làm tốt hơn.'),
(9, 29, 2, 'Không hài lòng với chất lượng sản phẩm.'),
(10, 30, 5, 'Rất tốt, sản phẩm đẹp và chất lượng vượt trội.');
